First PR to merge basic code.
anijit18/Brick_Breaker pull request #1
Opened 2023-05-07 08:11 UTC by anijit18

2023-05-07 08:13 UTC, invicta198 requested changes

2023-05-07 08:13 UTC, invicta198 commented on .idea/Brick_Breaker.iml
> +</module>
Add an empty line at the end.

2023-05-07 08:13 UTC, invicta198 commented on .idea/misc.xml
> +</project>
Same here.

2023-05-07 08:19 UTC, anijit18 commented on .idea/Brick_Breaker.iml
> +</module>
Done.

2023-05-07 08:20 UTC, anijit18 commented on .idea/misc.xml
> +</project>
Done.

2023-05-07 08:29 UTC, invicta198 requested changes

2023-05-07 08:29 UTC, invicta198 commented on Gameplay.java
> +//import java.util.Timer;
remove this comment

2023-05-07 08:29 UTC, invicta198 commented on Gameplay.java
> +    public void keyReleased(KeyEvent e) {}
If these functions have no use, remove them.

2023-05-07 08:30 UTC, invicta198 commented
learn about how to add function docstrings.
Example:
```
/**
   * This is the main method which makes use of addNum method.
   * @param args Unused.
   * @return Nothing.
   * @exception IOException On input error.
   * @see IOException
   */

   public static void main(String args[]) throws IOException {
      AddNum obj = new AddNum();
      int sum = obj.addNum(10, 20);

      System.out.println("Sum of 10 and 20 is :" + sum);
   }
```

2023-05-07 10:38 UTC, anijit18 commented on Gameplay.java
> +//import java.util.Timer;
Done.

2023-05-07 10:42 UTC, anijit18 commented on Gameplay.java
> +    public void keyReleased(KeyEvent e) {}
Main class implements KeyListener, therefore cannot remove implemented functions.

2023-05-07 11:35 UTC, invicta198 commented
Keep these files in your local but remove these files from GitHub

out/production/Brick_Breaker/Gameplay.class
out/production/Brick_Breaker/Main.class

2023-05-07 11:35 UTC, invicta198 commented on .idea/Brick_Breaker.iml
> +</module>
Not done.

2023-05-07 11:35 UTC, invicta198 commented on .idea/misc.xml
> +</project>
Not done.

2023-05-10 08:11 UTC, invicta198 approved these changes

2023-05-10 08:11 UTC, invicta198 commented on Main.java
> +
Remove extra whiteline

2023-05-10 08:12 UTC, merged